#%RAML 1.0 NamedExample
IndianFlightExample:

value:  
  -
    ID: 1
    code: ER234
    price: 400
    departureDate: 2023/02/04

  - 
    ID: 2
    code: ER235
    price: 400
    departureDate: 2023/02/04
